# SPDX-FileCopyrightText: 2023-2024 The LineageOS Project
# SPDX-License-Identifier: Apache-2.0

ifneq ($(WITHOUT_RESERVED_SIZE),true)
    ifeq ($(TARGET_BUILD_PACKAGE),1) # Vanilla build
        ifeq ($(PRODUCT_VIRTUAL_AB_OTA),true)
            BOARD_PRODUCTIMAGE_MINIMAL_PARTITION_RESERVED_SIZE ?= true
        endif
        ifneq ($(EXTRA_RESERVED_SIZE),true)
            BOARD_PRODUCTIMAGE_EXTFS_INODE_COUNT ?= -1
        endif
        ifeq ($(BOARD_PRODUCTIMAGE_MINIMAL_PARTITION_RESERVED_SIZE),true)
            BOARD_PRODUCTIMAGE_PARTITION_RESERVED_SIZE ?= 1188036608
        else
            BOARD_PRODUCTIMAGE_PARTITION_RESERVED_SIZE ?= 1957691392
        endif
        ifneq ($(EXTRA_RESERVED_SIZE),true)
            BOARD_SYSTEMIMAGE_EXTFS_INODE_COUNT ?= -1
            BOARD_SYSTEM_EXTIMAGE_EXTFS_INODE_COUNT ?= -1
        endif
        BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE ?= 94371840
        BOARD_SYSTEM_EXTIMAGE_PARTITION_RESERVED_SIZE ?= 94371840
    else ifeq ($(TARGET_BUILD_PACKAGE),3) # GApps build
        ifeq ($(EXTRA_RESERVED_SIZE),true)
            BOARD_PRODUCTIMAGE_PARTITION_RESERVED_SIZE ?= 104857600
            BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE ?= 104857600
            BOARD_SYSTEM_EXTIMAGE_PARTITION_RESERVED_SIZE ?= 104857600
        endif
    endif
endif
